application_context: ${DEV_APP_CONTEXT}

server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: bloomify-be-dev
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${DB_DEV_URL}
    username: ${DB_DEV_USERNAME}
    password: ${DB_DEV_PASSWORD}
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB


jwt-variables:
  secret-key: ${JWT_SECRET}
  expiration-time: 3600000

AmazonS3:
  S3_SECRET_KEY: ${S3_SECRET_KEY}
  S3_ACCESS_KEY: ${S3_ACCESS_KEY}
  S3_REGION: ${S3_REGION}
  S3_BUCKET_NAME: ${S3_BUCKET_NAME}
