spring:
  application:
    name: "bloomify-be"
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}



jwt-variables:
  EXPIRES_ACCESS_TOKEN_MINUTE: ${ACCESS_TOKEN_EXPIRE}
  EXPIRES_REFRESH_TOKEN_MINUTE: ${REFRESH_TOKEN_EXPIRE}
  ISSUER: dev
  KEY: ${JWT_KEY}